### ISSUE TITLE
Avatar size incorrect

### ISSUE THREAD

**Issue by AlynxZhou** [wzpan/comment.js#10]
![screenshot from 2018-04-15 15-05-31](https://user-images.githubusercontent.com/8444615/38775831-970f1cc2-40be-11e8-964e-b8211895b1b3.png)
The Image tag is set to 44x44, but the avatar is shown in 88x44, I don't know why...

**Comment by AlynxZhou** [comment]
另外我也不知道为什么，在 github 是正常的字体，到博客页面就是斜体了。。。

**Comment by wzpan** [comment]
你自己的博客主题和这个冲突，请自行解决css问题。

**Comment by AlynxZhou** [comment]
Bingo
