### ISSUE TITLE
创建了issue之后页面仍然显示无评论

### ISSUE THREAD

**Issue by AlynxZhou** [wzpan/comment.js#12]
<https://sh.alynx.xyz/posts/2018/06/04/Hexo-on-VPS-with-Nginx-and-HTTPS/>

就这个页面有问题……其他的没有这个问题

**Comment by wzpan** [comment]
@AlynxZhou 似乎是标题那个+号导致，被Github去掉了所以失去了关联。你可以通过设置 issue_id 强制关联 issue 号。例如把 issue_id 的设置放在文章头部的 front-matters 里头然后在模板里判断如果存在 issue_id 的设置就让 comment.js 读这个 issue 作为评论。

**Comment by AlynxZhou** [comment]
行吧，我把标题改了好了。。。
