### ISSUE TITLE
Uncaught ReferenceError: timeago is not defined

### ISSUE THREAD

**Issue by pylixm** [wzpan/comment.js#2]
Thanks for you work.

I config my blog comment  according to project readme docs. But it is not work . The error is 'Uncaught ReferenceError: timeago is not defined'. Can you help me？Thanks advance！

**Comment by wzpan** [comment]
Have you added timeago.min.js into your header?

``` html
<!-- stylesheet -->
<link rel="stylesheet" href="path_to_comment_css/comment.css">

<!-- javascripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.js">/script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown.js/0.5.0/markdown.min.js">/script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/timeago.js/3.0.2/timeago.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>
<script src="path_to_comment_js/comment.js"></script>
```

**Comment by wzpan** [comment]
@pylixm if it helps, please close the issue.

**Comment by pylixm** [comment]
Get it !  I did not import the js file correctly. 

In addition, the css has some confused and lose some style. 
`timeline-comment-label` lost `line-height: 40px;`

I can solve it. I hope new theme to come quickly . Thank  you a lot .
